apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ft-reg-003-drop-harbor
  namespace: kyverno
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 171.244.199.186/32
