apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.19.133
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-trvkz
      namespace: kyverno
      uid: 2c3776bb-2266-47a6-a5ae-24252248b41c
  - addresses:
    - 10.244.19.187
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-fvsdv
      namespace: kyverno
      uid: e020a128-7433-48c0-9d01-8b9932168a14
  - addresses:
    - 10.244.212.79
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-9fhc5
      namespace: kyverno
      uid: e86a7db3-7fc6-436d-8cb6-225ff8c05161
  - addresses:
    - 10.244.212.127
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-djlm2
      namespace: kyverno
      uid: 33f8a641-84a2-4b69-a92f-e353c3863eba
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-09-29T04:35:38Z"
    creationTimestamp: "2026-09-29T04:35:38Z"
    generateName: kyverno-svc-
    generation: 1
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.1
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: kyverno-3.9.1
      kubernetes.io/service-name: kyverno-svc
    name: kyverno-svc-2ggvq
    namespace: kyverno
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kyverno-svc
      uid: e9633748-540c-4315-b8b1-7fac2b9c5f6c
    resourceVersion: "34105771"
    uid: 6dec2ae6-1608-485d-8eaa-9017b9afd893
  ports:
  - appProtocol: https
    name: https
    port: 9443
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
