apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.212.71
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-875sb
      namespace: kyverno
      uid: 45888429-7647-4cec-8743-c739cd6744a9
  - addresses:
    - 10.244.212.75
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-wjf7t
      namespace: kyverno
      uid: f1e37b4c-f132-4b20-a915-baec64552d0c
  - addresses:
    - 10.244.19.189
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-2pq28
      namespace: kyverno
      uid: 667568ee-a647-4ebc-bb03-c9de5ecedf1a
  - addresses:
    - 10.244.19.191
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-6f755d9865-hknxs
      namespace: kyverno
      uid: d573511b-e83f-41c8-9fc8-92bd16d34829
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-09-29T07:44:13Z"
    creationTimestamp: "2026-09-29T04:35:38Z"
    generateName: kyverno-svc-
    generation: 17
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.1
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: kyverno-3.9.1
      kubernetes.io/service-name: kyverno-svc
    name: kyverno-svc-2ggvq
    namespace: kyverno
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kyverno-svc
      uid: e9633748-540c-4315-b8b1-7fac2b9c5f6c
    resourceVersion: "34158037"
    uid: 6dec2ae6-1608-485d-8eaa-9017b9afd893
  ports:
  - appProtocol: https
    name: https
    port: 9443
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
