apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
  creationTimestamp: "2026-09-29T04:35:38Z"
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno-admission-controller
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.9.1
    helm.sh/chart: kyverno-3.9.1
  name: kyverno-svc
  namespace: kyverno
  resourceVersion: "34158036"
  uid: e9633748-540c-4315-b8b1-7fac2b9c5f6c
spec:
  clusterIP: 10.107.208.194
  clusterIPs:
  - 10.107.208.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
