apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2026-09-22T10:44:54Z"
  creationTimestamp: "2026-09-05T09:45:21Z"
  labels:
    app: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.15.2
    chart: harbor
    endpoints.kubernetes.io/managed-by: endpoint-controller
    heritage: Helm
    release: harbor
  name: harbor
  namespace: harbor
  resourceVersion: "26889504"
  uid: b515f83a-fce8-4036-bd3b-b27ace1ce3d1
subsets:
- addresses:
  - ip: 10.244.19.153
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: harbor-nginx-688cf77c5b-7f6lh
      namespace: harbor
      uid: 3c217301-2b71-45f8-87b8-85eeb36304d1
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
