apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: restrict-added-capabilities
  labels:
    app.kubernetes.io/managed-by: kyverno
    policies.ksp.io/id: ksp-pod-009
  annotations:
    policies.kyverno.io/title: Restrict Added Capabilities
    policies.kyverno.io/category: KSP Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: Allows only NET_BIND_SERVICE when Linux capabilities
      are added.
    policies.ksp.io/profiles: restricted
    policies.ksp.io/dev-mode: Audit
    policies.ksp.io/staging-mode: Audit
    policies.ksp.io/prod-mode: Enforce
    policies.ksp.io/exception: controlled
spec:
  evaluation:
    background:
      enabled: true
  failurePolicy: Fail
  webhookConfiguration:
    timeoutSeconds: 10
  validationActions:
  - Audit
  - Warn
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: (((object.spec.containers + object.spec.?initContainers.orValue([])
      + object.spec.?ephemeralContainers.orValue([])))).all(c, c.?securityContext.capabilities.add.orValue([]).all(x,
      x == 'NET_BIND_SERVICE'))
    message: Only NET_BIND_SERVICE may be added as a Linux capability.

