apiVersion: v1
kind: Namespace
metadata:
  name: ksp-demo
  labels:
    ksp.io/environment: production
    ksp.io/profile: restricted
    app.kubernetes.io/name: demo-app
    policies.ksp.io/owner: platform-team
