
==========================================
BINDING=kyverno:admission-controller
ROLE=kyverno:admission-controller
==========================================
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.kyverno.io/aggregate-to-admission-controller: "true"
  - matchLabels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
  creationTimestamp: "2026-08-26T04:36:07Z"
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno-admission-controller
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.9.1
    helm.sh/chart: kyverno-3.9.1
  name: kyverno:admission-controller
  resourceVersion: "34099649"
  uid: dab1a764-d330-49c8-8bb1-1ada6ad57e49
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  - mutatingadmissionpolicies
  - mutatingadmissionpolicybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kyverno.io
  resources:
  - policies
  - policies/status
  - clusterpolicies
  - clusterpolicies/status
  - updaterequests
  - updaterequests/status
  - globalcontextentries
  - globalcontextentries/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - kyverno.io
  resources:
  - policyexceptions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.kyverno.io
  resources:
  - validatingpolicies
  - validatingpolicies/status
  - namespacedvalidatingpolicies
  - namespacedvalidatingpolicies/status
  - imagevalidatingpolicies
  - imagevalidatingpolicies/status
  - namespacedimagevalidatingpolicies
  - namespacedimagevalidatingpolicies/status
  - generatingpolicies
  - generatingpolicies/status
  - namespacedgeneratingpolicies
  - namespacedgeneratingpolicies/status
  - mutatingpolicies
  - mutatingpolicies/status
  - namespacedmutatingpolicies
  - namespacedmutatingpolicies/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - policies.kyverno.io
  resources:
  - policyexceptions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reports.kyverno.io
  resources:
  - ephemeralreports
  - clusterephemeralreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  - policyreports/status
  - clusterpolicyreports
  - clusterpolicyreports/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch

==========================================
BINDING=kyverno:admission-controller:view
ROLE=view
==========================================
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2026-08-26T02:32:12Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: view
  resourceVersion: "32262534"
  uid: ec1eeda2-fbbd-4df4-94f0-f92a9711f726
rules:
- apiGroups:
  - kyverno.io
  resources:
  - cleanuppolicies
  - clustercleanuppolicies
  - policies
  - clusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policies.kyverno.io
  resources:
  - deletingpolicies
  - generatingpolicies
  - imagevalidatingpolicies
  - mutatingpolicies
  - namespaceddeletingpolicies
  - namespacedgeneratingpolicies
  - namespacedimagevalidatingpolicies
  - namespacedmutatingpolicies
  - namespacedvalidatingpolicies
  - policyexceptions
  - validatingpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  - clusterpolicyreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reports.kyverno.io
  resources:
  - ephemeralreports
  - clusterephemeralreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kyverno.io
  resources:
  - updaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - daemonsets/status
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - cronjobs/status
  - jobs
  - jobs/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - daemonsets/status
  - deployments
  - deployments/scale
  - deployments/status
  - ingresses
  - ingresses/status
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicasets/status
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  - resourceclaims/status
  - resourceclaimtemplates
  verbs:
  - get
  - list
  - watch
