apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
  creationTimestamp: "2026-08-26T04:36:07Z"
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno-admission-controller
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.9.1
    helm.sh/chart: kyverno-3.9.1
  name: kyverno:admission-controller:view
  resourceVersion: "34099668"
  uid: 954270b1-72ed-4d6e-87b0-fadfb624bf53
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
