apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: background-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-background-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-background-controller-metrics
    namespace: kyverno
    resourceVersion: "32261735"
    uid: 349ee0ad-2e44-47c2-b321-8282c7c58de6
  spec:
    clusterIP: 10.107.63.253
    clusterIPs:
    - 10.107.63.253
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app.kubernetes.io/component: background-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: cleanup-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-cleanup-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-cleanup-controller
    namespace: kyverno
    resourceVersion: "32261736"
    uid: ff8f0e28-7016-4028-ad06-a41ba16ee3e1
  spec:
    clusterIP: 10.110.91.111
    clusterIPs:
    - 10.110.91.111
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/component: cleanup-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: cleanup-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-cleanup-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-cleanup-controller-metrics
    namespace: kyverno
    resourceVersion: "32261740"
    uid: cb04adaf-862c-4f07-94ad-04dd840d6cf4
  spec:
    clusterIP: 10.100.21.143
    clusterIPs:
    - 10.100.21.143
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app.kubernetes.io/component: cleanup-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: reports-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-reports-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-reports-controller-metrics
    namespace: kyverno
    resourceVersion: "32261742"
    uid: 6c1c4e5c-9027-41ed-a857-a935bb6a5df9
  spec:
    clusterIP: 10.107.183.80
    clusterIPs:
    - 10.107.183.80
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app.kubernetes.io/component: reports-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-svc
    namespace: kyverno
    resourceVersion: "32261730"
    uid: b2fa9b6b-36ef-45bc-a344-523b182478b0
  spec:
    clusterIP: 10.105.178.93
    clusterIPs:
    - 10.105.178.93
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2026-08-26T04:36:07Z"
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.9.0
      helm.sh/chart: kyverno-3.9.0
    name: kyverno-svc-metrics
    namespace: kyverno
    resourceVersion: "32261733"
    uid: 3fd207c2-126f-4cff-9bc5-289623a85efe
  spec:
    clusterIP: 10.111.119.194
    clusterIPs:
    - 10.111.119.194
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
