apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3ItcHVibGljOjMwMDAzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IkhhcmJvcjEyMzQ1IiwiYXV0aCI6IllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSJ9fX0=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".dockerconfigjson":"eyJhdXRocyI6eyJoYXJib3ItcHVibGljOjMwMDAzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IkhhcmJvcjEyMzQ1IiwiYXV0aCI6IllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSJ9fX0="},"kind":"Secret","metadata":{"annotations":{},"name":"harbor-registry-credentials","namespace":"kyverno"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: "2026-09-06T17:04:14Z"
  name: harbor-registry-credentials
  namespace: kyverno
  resourceVersion: "4086641"
  uid: f5e00201-bc90-45bb-8c4b-af751d76c6bb
type: kubernetes.io/dockerconfigjson
