apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2026-10-01T02:30:22Z"
  labels:
    app.kubernetes.io/managed-by: kyverno
    generate.kyverno.io/policy-name: generate-resource-quota
    generate.kyverno.io/trigger-group: ""
    generate.kyverno.io/trigger-kind: Namespace
    generate.kyverno.io/trigger-name: ft-rbac-008-baseline
    generate.kyverno.io/trigger-namespace: ""
    generate.kyverno.io/trigger-uid: bb9c7d7b-3879-4e06-9256-8b7a72281d2e
    generate.kyverno.io/trigger-version: v1
    policies.ksp.io/environment: dev
    policies.ksp.io/generated-by: ksp-res-005
    policies.ksp.io/quota-class: small
  name: namespace-resource-quota
  namespace: ft-rbac-008-baseline
  resourceVersion: "34842462"
  uid: f9aad4c0-4e9a-4210-b8b2-caa921595963
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "25"
    requests.cpu: "2"
    requests.memory: 4Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "25"
    requests.cpu: "2"
    requests.memory: 4Gi
  used:
    limits.cpu: "0"
    limits.memory: "0"
    pods: "0"
    requests.cpu: "0"
    requests.memory: "0"
