apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{"meta.helm.sh/release-name":"kyverno","meta.helm.sh/release-namespace":"kyverno"},"creationTimestamp":"2026-08-26T04:36:07Z","labels":{"app.kubernetes.io/component":"background-controller","app.kubernetes.io/instance":"kyverno","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kyverno-background-controller","app.kubernetes.io/part-of":"kyverno","app.kubernetes.io/version":"3.9.1","helm.sh/chart":"kyverno-3.9.1"},"name":"kyverno:background-controller:view","resourceVersion":"34099670","uid":"7de53cda-f80b-4fe1-aeff-788df2e7a03c"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"view"},"subjects":[{"kind":"ServiceAccount","name":"kyverno-background-controller","namespace":"kyverno"}]}
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
  creationTimestamp: "2026-10-01T01:57:55Z"
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno-background-controller
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.9.1
    helm.sh/chart: kyverno-3.9.1
  name: kyverno:background-controller:view
  resourceVersion: "34833300"
  uid: fb0bd512-8ac2-4acf-b245-4be0fd53c726
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
