apiVersion: v1
kind: Pod
metadata:
  name: harbor-signed-e2e
  namespace: harbor-test
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-node-2

  imagePullSecrets:
    - name: harbor-registry-credentials

  containers:
    - name: app
      image: harbor-public:30003/ksp-test/signed@sha256:b7f3d86d6e84fc17718c48bcde1450807faa2d56704205c697b4bd5df7b9e29f
      imagePullPolicy: Always

      command:
        - sh
        - -c
        - sleep 3600

      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false