apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.19.153
    conditions:
      ready: false
      serving: false
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: ft-adm-009-notready
      namespace: kyverno
      uid: c2d5dabb-a45d-4dc1-9d4f-edd9683a8e74
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2026-09-18T07:43:07Z"
    generateName: kyverno-svc-
    generation: 1
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.8.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: kyverno-3.8.2
      kubernetes.io/service-name: kyverno-svc
    name: kyverno-svc-5c8lr
    namespace: kyverno
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kyverno-svc
      uid: b2fa9b6b-36ef-45bc-a344-523b182478b0
    resourceVersion: "16141780"
    uid: a5c622e0-47e3-42a2-b790-9d526646237e
  ports: null
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.212.126
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-54d58cc467-z24lv
      namespace: kyverno
      uid: 867eef31-ed3e-4149-a5dd-1a9921adbc76
  - addresses:
    - 10.244.212.127
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-1
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-54d58cc467-r8lnt
      namespace: kyverno
      uid: c9ca0281-42d5-40fc-be90-0df51b7ad58e
  - addresses:
    - 10.244.19.146
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: worker-node-2
    targetRef:
      kind: Pod
      name: kyverno-admission-controller-54d58cc467-t2qwb
      namespace: kyverno
      uid: e083d4e0-359d-43d7-b08e-9834b293ef8f
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-09-18T07:41:45Z"
    creationTimestamp: "2026-08-26T04:36:07Z"
    generateName: kyverno-svc-
    generation: 377
    labels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno-admission-controller
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: 3.8.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: kyverno-3.8.2
      kubernetes.io/service-name: kyverno-svc
    name: kyverno-svc-986g8
    namespace: kyverno
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kyverno-svc
      uid: b2fa9b6b-36ef-45bc-a344-523b182478b0
    resourceVersion: "16138767"
    uid: 9c0e10da-fb6d-41d2-81eb-65b6edb98926
  ports:
  - appProtocol: https
    name: https
    port: 9443
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
