grafana:
  enabled: true

  grafana.ini:
    plugins:
      preinstall_auto_update: false
prometheus:
  enabled: true
  prometheusSpec:
    retention: 14d
    retentionSize: "10GB"
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

alertmanager:
  enabled: true

prometheusOperator:
  enabled: true
